#### 函数库导入

In [2]:
import torch
import torch.nn as nn
from basic_model import DeepModel_single, gradients

#### 模型参数
$$
    y = f(x;\xi)\\
    x: N_1, N_2, N_3, ..., M 矩阵\\
    y: N_1, N_2, N_3, ..., N 矩阵\\
$$


In [10]:
# 构建网络
Net = DeepModel_single([2] + [32] *4 + [5], active=nn.ReLU())
print(Net.layers)
# 给定输入
x1 = torch.randn((100, 2), dtype=torch.float32)
# 计算输出
y1 = Net(x1)
print(y1.shape)
print(y1)

Sequential(
  (0): Linear(in_features=2, out_features=32, bias=True)
  (1): ReLU()
  (2): Linear(in_features=32, out_features=32, bias=True)
  (3): ReLU()
  (4): Linear(in_features=32, out_features=32, bias=True)
  (5): ReLU()
  (6): Linear(in_features=32, out_features=32, bias=True)
  (7): ReLU()
  (8): Linear(in_features=32, out_features=5, bias=True)
)
torch.Size([100, 5])
tensor([[-1.3622e-01, -4.6355e-03, -8.2130e-02,  6.2221e-02,  1.4175e-02],
        [-6.1433e-02, -3.6541e-02, -1.5348e-02, -4.6025e-03,  1.6585e-02],
        [-9.2232e-02,  3.2094e-02, -7.9484e-02,  5.5920e-02,  7.6683e-02],
        [-2.7922e-01, -7.2839e-02, -1.5803e-01,  1.2849e-01,  1.5421e-03],
        [-6.9191e-02,  2.5886e-02, -9.0205e-02,  6.0533e-02,  7.0029e-02],
        [-3.5182e-01,  2.0040e-02, -2.5587e-01,  2.0174e-01,  7.9369e-02],
        [-6.4892e-02,  1.0024e-02, -7.5548e-02,  6.6817e-02,  2.6890e-02],
        [-2.5082e-01, -5.9414e-03, -1.5137e-01,  1.1458e-01,  2.6273e-02],
        [-5.6176e-02,

In [11]:
# 给定输入
x2 = torch.randn((100, 300, 2), dtype=torch.float32)
# 计算输出
y2 = Net(x2)
print(y2.shape)
print(y2)

torch.Size([100, 300, 5])
tensor([[[-2.3551e-01,  2.3036e-02, -1.8128e-01,  1.3646e-01,  4.5246e-02],
         [-1.0338e-01,  1.7754e-02, -9.1428e-02,  9.1999e-02,  1.0414e-01],
         [-3.1548e-01,  3.1402e-02, -2.4157e-01,  1.8016e-01,  5.7826e-02],
         ...,
         [-2.6542e-02, -1.5427e-02, -7.2658e-03, -2.9224e-03,  8.4530e-03],
         [-2.1850e-01,  1.0394e-02, -1.6093e-01,  1.2603e-01,  5.4715e-02],
         [-4.6662e-01,  3.5920e-02, -3.2400e-01,  2.4163e-01,  6.6018e-02]],

        [[-5.3117e-02, -2.4145e-02, -1.6236e-02,  1.2952e-02,  6.0431e-04],
         [-8.5253e-02,  2.8481e-02, -8.4392e-02,  6.5958e-02,  7.7955e-02],
         [-7.8759e-02, -3.2889e-03, -5.9194e-02,  3.5152e-02,  7.9060e-02],
         ...,
         [-4.9288e-02, -2.9389e-02, -1.1979e-02, -2.6843e-03,  1.1877e-02],
         [-4.9694e-02,  2.5933e-02, -7.7519e-02,  9.4866e-02,  1.0506e-01],
         [-8.6059e-02, -1.9972e-02, -2.6652e-02,  3.6125e-02, -1.2012e-02]],

        [[-7.5856e-02, -4.3588

In [13]:
# 给定输入
x3 = torch.randn((100, 300, 5, 2), dtype=torch.float32)
# 计算输出
y3 = Net(x3)
print(y3.shape)
print(y3)

torch.Size([100, 300, 5, 5])
tensor([[[[-9.7617e-02,  3.4692e-02, -8.3645e-02,  5.9466e-02,  8.4984e-02],
          [-2.8568e-02,  2.9400e-03, -3.1680e-02,  2.5461e-02,  1.0458e-02],
          [-2.1201e-02,  9.1251e-03, -4.9491e-02,  5.2887e-02,  3.6170e-02],
          [-1.0583e-02,  4.6765e-03, -2.5367e-02,  2.7675e-02,  1.9078e-02],
          [-1.4962e-01, -1.0038e-02, -1.1168e-01,  6.0852e-02,  1.4799e-01]],

         [[-1.0522e-01,  1.9455e-02, -1.0724e-01,  1.1214e-01,  1.1308e-01],
          [-8.6226e-02,  7.1327e-03, -7.1137e-02,  5.1468e-02,  2.6277e-02],
          [-1.6914e-01, -9.0509e-02, -4.7848e-02,  2.9883e-02,  4.7735e-03],
          [-2.2327e-01,  1.4610e-02, -1.4983e-01,  1.1171e-01,  2.7905e-02],
          [-7.8522e-02,  1.4129e-02, -7.4673e-02,  7.6746e-02,  8.1719e-02]],

         [[-4.9657e-02, -1.6253e-02, -1.5691e-02,  1.7480e-02, -4.4757e-03],
          [-8.1066e-02, -4.6248e-02, -1.8015e-02,  4.3276e-03,  9.9968e-03],
          [-3.5204e-01,  1.7285e-02, -2.637

### 一阶导数

In [6]:
# 给定输入
x = torch.ones((10, 5, 4, 3, 2), dtype=torch.float32)
# 注意必须将自变量的梯度置为true，才能求自动微分
x.requires_grad_(True)
# 计算输出，前向过程
y = Net(x)
# 计算y对x的一阶微分，反向过程
dydx = gradients(y, x)
print(dydx.shape)
print(dydx)

torch.Size([10, 5, 4, 3, 2, 5])
tensor([[[[[[ 0.0967, -0.1089,  0.1132, -0.0206,  0.0699],
            [-0.0378,  0.1140,  0.1111, -0.0678,  0.0017]],

           [[ 0.0967, -0.1089,  0.1132, -0.0206,  0.0699],
            [-0.0378,  0.1140,  0.1111, -0.0678,  0.0017]],

           [[ 0.0967, -0.1089,  0.1132, -0.0206,  0.0699],
            [-0.0378,  0.1140,  0.1111, -0.0678,  0.0017]]],


          [[[ 0.0967, -0.1089,  0.1132, -0.0206,  0.0699],
            [-0.0378,  0.1140,  0.1111, -0.0678,  0.0017]],

           [[ 0.0967, -0.1089,  0.1132, -0.0206,  0.0699],
            [-0.0378,  0.1140,  0.1111, -0.0678,  0.0017]],

           [[ 0.0967, -0.1089,  0.1132, -0.0206,  0.0699],
            [-0.0378,  0.1140,  0.1111, -0.0678,  0.0017]]],


          [[[ 0.0967, -0.1089,  0.1132, -0.0206,  0.0699],
            [-0.0378,  0.1140,  0.1111, -0.0678,  0.0017]],

           [[ 0.0967, -0.1089,  0.1132, -0.0206,  0.0699],
            [-0.0378,  0.1140,  0.1111, -0.0678,  0.0017]],

    

### 二阶导数

In [15]:
# 计算y对x的二阶微分，反向过程，注意求导机制，保证除最后一个维度外对x都是独立的
d2ydx2 = gradients(dydx[..., (0,)], x)
print(d2ydx2.shape)
print(d2ydx2)

torch.Size([10, 5, 4, 3, 2])
tensor([[[[[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0., 0.]]],


         [[[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0., 0.]],

          [[0., 0.],
           [0., 0.],
           [0

In [8]:
# 模型验证